#!/bin/sh

KOGAION_LOADER="/usr/bin/xdg-open"
KOGAION_URL=${KOGAION_URL:-http://www.kogaion.ro?install_welcome=1}

# load Sabayon URL
[[ -x "${KOGAION_LOADER}" ]] && ${KOGAION_LOADER} ${KOGAION_URL} &

# remove myself from autostart
rm ~/.config/autostart/kogaion-welcome-loader.desktop -f
